services:
  - type: web
    name: bid-for-credit
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: BASE_URL
        sync: false
